sudo: false
language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run build
- npm run cover
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: 282387881@qq.com
  api_key:
    secure: eHzo0szyPyHPsyExLqwbkEKSkoYUy7FoY9so06EUdDurmAI6vXOEhdH7eIlLR3jnC2hA+s5Dpibag7am5a5IF0MAWZM+KE/BgqeEG42f0bc2ul/jn+boBCh6BRIEWYIExJEZiTYae0iDSvaVqOO+oEneY8uwZs7dL0bmFhjJuS+uJH5QGAEOqM1MAvtQ9eACxOrOLXF1wRXIggk1r1c3hFvcHW4srkNbm3Pv/JCThPGmJhaVK5dOPoQeRX5x3zXXPSdgp8PEvGzW0CeK+tF8hxiars3A9fccZbTIuH4aYHldVcU20YvuBeqjtMEZzFP7JZkxJbNLT6PPcPLJLSsv0rNmpf5luzwDKw6vFRfY+9QSqv3gkyMd1TZwAYvGuvjhQ1TukqA2gHAjhT9/8obdRnmt90InL8hPydl29Wocuu4wE5HhqVqieZO3OrmXisELPXqkhect+G6CWDeb3NCuoga3lV0ktyvMdg20oFPo/W4me8EMOLEscchdsj9iHRzDiJhRen5qfnrJ+VFqGm4Pv17+AChtgj84TPW4vp8sMcO9K9sWVEdHQwpmKhJvqt9/MTNqBszOSUkD8s8+aciQeL49MZiVv1RGLnFeCkCwuAmWUVzF6Eb642JM30mjvnm1ra3Ar/bQ51OuMze0Vws8dgyRwLAQDJpH7lCo86/goOg=
  on:
    tags: false
    repo: Sarmay/sarmay-web-ime
    branch: main
  skip_cleanup: true
  tag: next
