sudo: false
language: node_js
node_js:
- node
install:
- npm install
script:
- npm run lint
- npm run build
- npm run cover
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: 282387881@qq.com
  api_key:
    secure: GdNc/cujPZrcu9LSiDMfEPppsU1WKSXbKeYC2KSnFTDmXQJRAqJsyJip2K/dGqyIH+//h1GG5LDM0IjwHRWm6Ljw6x6aohcm3cZtXbDfmNOfIOmaLFQiJBWmJ+q/SvIjvh1CzZA+plDt06VFjBHSrcTOlo0ekdsmB6HnMc027kPVOHmYjpeugSunVLUwX0KOUR3QIgZlfyYjYUg/hPs+vaVXhbvJfGAgd2qRgzCYsbqRQ9wkXc4wMYTAcNA1YTyIWCEA7T/LFGznG3B+bZm11fFKeiojKc9JmexUWxNehaA92AQa18iHE0I9yGET5OUlLywehVwInw6icFExx1voXcGOcYVLa+guOsntEH1dq5b9+e0SbbiKNshPUnSk2Q4sn5BO3Zr4f7Y3q1UEn7L5VBtpWgSi3OomGiCbcKSDB4M+BDul5vKmpYSuTmmDlQocIc+PCkQvOh9/VILThfs6aHw6VNYJ08YMaBTjTNFzYt/Ps9U1XJWSS61alfLPEU7w25K8oM5AIGDHpkpfCtMjL+QI6Q36mwWhi958M6Xiq+DPV6Im92oZWW+dLTCKtiey9bOtDwra7C+6F2oPg5Zlky5+bhAc+wVPisGSKQdfZ6o+6UNwarqxTLdFbJqWcGCGi9z4z6AMvqJSJA1oAprvlyZd5tu1tw49CXzP/UgyKLE=
  on:
    tags: false
    repo: Sarmay/sarmay-web-ime
    branch: main
  skip_cleanup: true
  tag: next